name: Linter y tests

on:
  pull_request:
    branches:
      - master
    types: [opened, reopened, synchronize]

jobs:
  linter_y_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          #registry-url: "https://npm.pkg.github.com"
      - run: |
          if [ -e yarn.lock ]; then
            yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
            npm ci
          else
            npm i
          fi
      - run: npm run lint
      - run: npm run test

  build-test-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: 'Determine tag'
        run: 'echo "RELEASE_TAG=0.0.1" >> $GITHUB_ENV'

      - name: Build the Docker image
        run: docker build . -t cloudnativerioja/official-website:${{ env.RELEASE_TAG }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'cloudnativerioja/official-website:${{ env.RELEASE_TAG }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Run the Docker image
        run: docker run -d -p 8080:80 cloudnativerioja/official-website:${{ env.RELEASE_TAG }}

      - name: Test the Docker image
        run: sleep 5 && curl -sSf localhost:8080 | grep -q 'Cloud Native Rioja'
