name: Pull Request

on:
  pull_request:
    branches:
      - master
    types: [opened, reopened, synchronize]

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          #registry-url: "https://npm.pkg.github.com"
      - run: |
          if [ -e yarn.lock ]; then
            yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
            npm ci
          else
            npm i
          fi
      - run: npm run lint
      - run: npm run test
      - uses: artiomtr/jest-coverage-report-action@v2.2.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          #   threshold: 80 # optional parameter auto-reject if below.
      # - run: npm run build
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
