name: Linter y tests

on:
  pull_request:
    branches:
      - master
    types: [opened, reopened, synchronize]

jobs:
  linter_y_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          #registry-url: "https://npm.pkg.github.com"
      - run: |
          if [ -e yarn.lock ]; then
            yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
            npm ci
          else
            npm i
          fi
      - run: npm run lint
      - run: npm run test
